# Generated by Django 2.0.3 on 2020-10-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201031_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indication',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_efect',
        ),
        migrations.RemoveField(
            model_name='product',
            name='therapeutic_class',
        ),
    ]
