# Generated by Django 2.0.3 on 2020-11-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201031_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_us',
        ),
        migrations.DeleteModel(
            name='beauty_care',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='corona',
        ),
        migrations.DeleteModel(
            name='health_care',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='slider',
        ),
        migrations.DeleteModel(
            name='store_location',
        ),
        migrations.DeleteModel(
            name='tips',
        ),
        migrations.DeleteModel(
            name='user_message',
        ),
    ]
