# Generated by Django 2.0.3 on 2020-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20201101_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='giftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'giftcard',
                'verbose_name_plural': 'giftcards',
            },
        ),
    ]
