# Generated by Django 2.0.3 on 2020-11-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_giftcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
