# Generated by Django 2.0.3 on 2020-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
