# Generated by Django 2.0.3 on 2020-11-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_giftcard_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='price',
            new_name='amount',
        ),
    ]
