# Generated by Django 2.0.3 on 2020-11-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vat',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='blogapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_reg',
            field=models.ForeignKey(blank=True, default=23, on_delete=django.db.models.deletion.CASCADE, to='blogapp.user_reg'),
            preserve_default=False,
        ),
    ]
