# Generated by Django 2.0.3 on 2020-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20201102_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_reg',
        ),
    ]
